### ISSUE TITLE
How to initialize the not empty board?

### ISSUE THREAD

**Issue by tidus2020** [dna2ai/gnugo.js#1]
How to initialize the not empty board?

How to get the winner?

**Comment by tidus2020** [comment]
作者是中国人？那我就不用我蹩脚英文了，这个要如何初始化残局？还有局势判断，胜负判断怎么做呢？

**Comment by dna2github** [comment]
不好意思，才注意有个open issue。这个你可以看README，

或者你可以看 test.html

https://github.com/dna2ai/gnugo.js/blob/main/test.html#L35 如何初始化

https://github.com/dna2ai/gnugo.js/blob/main/test.html#L41 如何得到下一步

gnugo.js 里暂时还没有暴露胜负判断的API，暂时需要手动 `Module._getBoard(i, j)` 得到所有棋子的状态然后自行判断。

或者你可以直接查看gnugo是如何判断胜负和预测下一步的，然后调用它的API，在 https://github.com/dna2ai/gnugo.js/blob/main/gnugowrapper.c 加上你的函数，并且重新编译一遍。

https://github.com/dna2ai/gnugo.js/blob/main/gnugowrapper.c#L170-L171 是如何计算当前分数score

`genNextStep` 是可以得到电脑推荐的下一步棋怎么走
